<?php

namespace App\Filament\Student\Resources\Fees;

use App\Filament\Student\Resources\Fees\Pages\CreateFee;
use App\Filament\Student\Resources\Fees\Pages\EditFee;
use App\Filament\Student\Resources\Fees\Pages\ListFees;
use App\Filament\Student\Resources\Fees\Pages\ViewFee;
use App\Filament\Student\Resources\Fees\Schemas\FeeForm;
use App\Filament\Student\Resources\Fees\Schemas\FeeInfolist;
use App\Filament\Student\Resources\Fees\Tables\FeesTable;
use App\Models\Fee;
use App\Models\Recovery;
use App\Models\Student;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class FeeResource extends Resource
{
    protected static ?string $model = Recovery::class;

    protected static string|BackedEnum|null $navigationIcon = 'hugeicons-cash-01';

    protected static ?string $recordTitleAttribute = 'Fee';
    protected static ?string $navigationLabel = 'Fee';
    protected static ?string $modelLabel = 'Fee';

    public static function canCreate(): bool
    {
        return false;
    }

    public static function canEdit(Model $record): bool
    {
        return false;
    }


    public static function getEloquentQuery(): Builder
    {
        $loggedInStudent = Student::where('user_id',auth()->id())->first();
        return parent::getEloquentQuery()
        ->where('student_id', $loggedInStudent->id);
        // TODO: Change the autogenerated stub
    }


    public static function form(Schema $schema): Schema
    {
        return FeeForm::configure($schema);
    }

    public static function infolist(Schema $schema): Schema
    {
        return FeeInfolist::configure($schema);
    }

    public static function table(Table $table): Table
    {
        return FeesTable::configure($table);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListFees::route('/'),
            'create' => CreateFee::route('/create'),
            'view' => ViewFee::route('/{record}'),
//            'edit' => EditFee::route('/{record}/edit'),
        ];
    }
}
